### ISSUE TITLE
(議論用issue) コラムを管理し掲載できるやうにする

### ISSUE THREAD

**Issue by ne-sachirou** [Ranyuen/web#72]
急いで。
#56 から引き継ぎ。
- [x] お知らせ記事をDB (MySQL) に格納する。 #73 
- [x] お知らせをtag分け。複数つけたtagの内、ひとつを選んで「主要」と印づけられるやうに。 #77
- [x] 管理者 #63 
- [x] 記事の作成、編集、削除page #74
